[package]
name = "new-fork-messenger"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/new-fork-messenger.rs"
crate-type = ["cdylib"]

[dependencies]
github-flows = "0.2"
slack-flows = "0.2.5"
tokio_wasi = { version = "1.25.1", features = ["macros", "rt"] }
anyhow = "1"
serde_json = "1"
